# Generated by Django 4.2.3 on 2023-07-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_turma', '0002_categoria_post_image_post_imagens_de_alter_post_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
